### ISSUE TITLE
Something is wrong with the audio

### ISSUE THREAD

**Issue by StopmotionSimonYT** [JasonLovesDoggo/RedditVideoMakerBot#15]
I have already tried cleaning the temp folder. Most of the time I get this error:
````
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Saving Text to MP3 files 🎶                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Saving... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Traceback (most recent call last):
  File "C:\Users\simon\AppData\Local\Programs\Python\Python310\lib\site-packages\mutagen\_util.py", line 251, in _openfile
    fileobj = open(filename, "rb+" if writable else "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'assets/temp/mp3/1.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Simon\RedditVideoMakerBot\video_creation\voices.py", line 38, in save_text_to_mp3
    length += MP3(f"assets/temp/mp3/{idx}.mp3").info.length
  File "C:\Users\simon\AppData\Local\Programs\Python\Python310\lib\site-packages\mutagen\_file.py", line 48, in __init__
    self.load(*args, **kwargs)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python310\lib\site-packages\mutagen\_util.py", line 154, in wrapper
    with _openfile(self, filething, filename, fileobj,
  File "C:\Users\simon\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python310\lib\site-packages\mutagen\_util.py", line 272, in _openfile
    raise MutagenError(e)
mutagen.MutagenError: [Errno 2] No such file or directory: 'assets/temp/mp3/1.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Simon\RedditVideoMakerBot\main.py", line 39, in <module>
    main()
  File "D:\Simon\RedditVideoMakerBot\main.py", line 30, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "D:\Simon\RedditVideoMakerBot\video_creation\voices.py", line 40, in save_text_to_mp3
    length = sox.file_info.duration(f"assets/temp/mp3/{idx}.mp3")
  File "C:\Users\simon\AppData\Local\Programs\Python\Python310\lib\site-packages\sox\file_info.py", line 121, in duration
    validate_input_file(input_filepath)
  File "C:\Users\simon\AppData\Local\Programs\Python\Python310\lib\site-packages\sox\file_info.py", line 248, in validate_input_file
    raise IOError(
OSError: input_filepath assets/temp/mp3/1.mp3 does not exist.
````

**Comment by StopmotionSimonYT** [comment]
No i fixed it

**Comment by StopmotionSimonYT** [comment]
Sorry for my short answer. I thought I fixed it but it didn't work.

**Comment by JasonLovesDoggo** [comment]
Again, could you share how you fixed it?

I still don't have the complete answer myself.

**Comment by JasonLovesDoggo** [comment]
You don't need the exe added to path.
I'm sorry about that though I can't fix it today I have other things. I will try to fix on Friday though

**Comment by binbohrawa** [comment]
Can I somehow filter desired comments, for eg, a vid I created has only one comment and it's a bot comment

**Comment by JasonLovesDoggo** [comment]
> 

you could check the comment's content before screenshotting and adding it the TTS queue

**Comment by binbohrawa** [comment]
Did you manage to fix the previous issue, I was checking others' method and I see that a guy here added a "results" folder, I did the same but it doesn't work after the mp3 extraction, it stuck at the DARK theme phase
