### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by Anjo8021** [JasonLovesDoggo/RedditVideoMakerBot#82]
When run main.py I get this error
![Desktop Screenshot 2022 06 10 - 12 26 17 90 (2)](https://user-images.githubusercontent.com/105073002/173055836-d389d1c1-a91e-42d0-b844-0ba750d71917.png)

**Comment by JasonLovesDoggo** [comment]
Fixed in latest version

**Comment by Anjo8021** [comment]
> Fixed in latest version

which version?

**Comment by aceIsHere** [comment]
Yes, the issue still persists. I am using the latest master file as well but issue is quite similar to #71

**Comment by JasonLovesDoggo** [comment]
At the emergency room and I can't help you rn

**Comment by aceIsHere** [comment]
No worries, Take your time. not demanding as such ;)

**Comment by JasonLovesDoggo** [comment]
fixed
